### ISSUE TITLE
Do not add Platypus created app to notification center

### ISSUE THREAD

**Issue by JP-NYC** [sveinbjornt/Platypus#150]
All apps I create with Platypus all show up in System Prefs -> Notifications Center.
Is there a way to not have every app I create show up in the notification Center?

**Comment by sveinbjornt** [comment]
All Platypus-generated apps have the ability to send messages to notification centre via the NOTIFICATION: syntax. But perhaps this should be configurable.

**Comment by JP-NYC** [comment]
Is there any plist setting that I could modify in the Platypus app (or other modification to the app) that would not register it with the Notification Center? Or is there any plist setting for the Notification Center to exclude an app?

**Comment by peetinc** [comment]
I'm just putting a big +1 on this issue. As I'm new to making apps with Platypus, I'm sure there's huge value in Notification Center integration. However, my first app is a LaunchAgent helper that really should remain silent. 

So a thumbs up for allowing this to be selectable so an app doesn't even attempt to register. 

@sveinbjornt In the mean time, is there anything that can be done manually to a project/profile/app to disable registering with Notification Center? Thanks a million.

**Comment by sveinbjornt** [comment]
This seems like a non-issue to me. What's the harm of an app showing up in the Notification Centre list even if it doesn't actually send any notifications? The list of apps is already very long, and it's not as if many users generally spend a lot of time in the Notifications pane of System Preferences.

The thing is, the app doesn't register as a notification sender via the Info.plist or anything like that. It actually happens at runtime, when the app is launched. You could disable notification support in the app by commenting out the following lines in ScriptExecController.m and building the app yourself:

```
- (BOOL)userNotificationCenter:(NSUserNotificationCenter *)center shouldPresentNotification:(NSUserNotification *)notification {
    return YES;
}
 ```

and also:

````
[[NSUserNotificationCenter defaultUserNotificationCenter] setDelegate:self];
````

I might make this configurable in the next version of Platypus, after I find the time to do more work on it, but on the whole I try to keep the number of configurable options to a minimum for the sake of simplicity.

**Comment by peetinc** [comment]
If it wasn't for Catalina's privacy controls, I'd agree. If the app silently registered in Notifications as it used to that'd be a non issue. The real problem is in Catalina. With the new privacy controls, at runtime the app prompts the user to allow it to send notifications even if the app doesn't attempt to send any notifications. 

If an app that does send notifications, that's a prompt the enduser should see (or one that the MDM provider should pre-aprove), if there are no notifications present in the app, the end user really shouldn't be bothered having to approve or disapprove allowing the app to send them notifications. I'm really trying my best to cut down on notification fatigue for my users.

Thanks a million for the response.peet

**Comment by sveinbjornt** [comment]
Ah, now I understand! I haven't made the leap to Catalina yet and am still running Mojave. What you describe is a serious and real usability problem. Will fix for next version release.

**Comment by xirianlight** [comment]
Poking this sleeping ticket as I'm testing progress bar UI's in Platypus in Big Sur. Any chance of an update, or perhaps a bit more clarification on how we can manually do this for an app?

**Comment by sveinbjornt** [comment]
Fixed in master.

**Comment by JP-NYC** [comment]
you say you fixed this issue in the master, but the latest version I just downloaded appears to still add Platypus created app to notification center


________________________________

**Comment by sveinbjornt** [comment]
Could you try now w. latest master?

**Comment by JP-NYC** [comment]
Just downloaded and tried v5.3 (1113)

it still shows in the notification center and I dont see a way to disable that


________________________________

**Comment by sveinbjornt** [comment]
In master means that it's been fixed on the master branch. Version 5.3 was released in 2018. If you want the absolutely latest, you'll have to build it yourself for now until I get around to releasing 5.4.
